In [4]:
import pandas as pd
import numpy as np

In [6]:
"""
Question 1:
Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2
"""

numpy_array = np.array([10,20,30,40,50])
numpy_array_add = numpy_array+2
numpy_array_mul = numpy_array*3
numpy_array_div = numpy_array/2

print("Original NumPy 1D-array                  : ",numpy_array)
print("Adding 2 to all the elements             : ",numpy_array_add)
print("Multiplying 3 with all the elements      : ",numpy_array_mul)
print("Dividing every element by 2              : ",numpy_array_div)

Original NumPy 1D-array                  :  [10 20 30 40 50]
Adding 2 to all the elements             :  [12 22 32 42 52]
Multiplying 3 with all the elements      :  [ 30  60  90 120 150]
Dividing every element by 2              :  [ 5. 10. 15. 20. 25.]


In [60]:
"""
Question 2:
Questions on Basic NumPy Array:
    a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
    b) Find the most frequent value and their indice(s) in the following arrays:
        i. x = np.array([1,2,3,4,5,1,2,1,1,1])
        ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
"""

arr=np.array([1,2,3,6,4,5])
print("Original NumPy array    : ",arr)
print("Reversing the array     : ",arr[::-1])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
counts_x = np.bincount(x)
most_frequent_value_x = np.argmax(counts_x)
indices_x = np.where(x == most_frequent_value_x)[0]

print("\nArray x:", x)
print(f"Most frequent value in x: {most_frequent_value_x}, Indices: {indices_x}")

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts_y = np.unique(y, return_counts=True)
max_count = np.max(counts_y)  
most_frequent_values_y = values[counts_y == max_count]  

print("\nArray y:", y)
print("Most frequent values in y:", most_frequent_values_y)
for value in most_frequent_values_y:
    indices_y = np.where(y == value)[0]
    print(f"Value: {value}, Indices: {indices_y}")


Original NumPy array    :  [1 2 3 6 4 5]
Reversing the array     :  [5 4 6 3 2 1]

Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value in x: 1, Indices: [0 5 7 8 9]

Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent values in y: [1 3]
Value: 1, Indices: [0 1 2]
Value: 3, Indices: [4 8 9]


In [20]:
"""
Question 3:
For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column
"""

arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Accessing 1st row, 2nd column  : ",arr[0][1])  # can also use arr[0,1] 
print("Accessing 3rd row, 1st column  : ",arr[2][0])  # can also use arr[2,0]

Accessing 1st row, 2nd column  :  20
Accessing 3rd row, 1st column  :  70


In [52]:
"""
Question 4:
Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?
"""

Karan = np.linspace(10,100,25)
print("Create 1-D NumPy array named Karan             : ", Karan)

print("\nDimension of the array                         : ", Karan.ndim)
print("Shape of the array                             : ", Karan.shape)
print("Total elements in the array                    : ", Karan.size)
print("Data type of each element                      : ", Karan.dtype)
print("Total number of bytes consumed by the array    : ", Karan.itemsize*Karan.size)      # or you can directly use Karan.nbytes

reshaped_karan = Karan.reshape(5,5)
print("\nArray after using reshape(5,5)                 :\n", reshaped_karan)
print("\nTranspose of the array using reshape()         :\n", reshaped_karan.T)

Create 1-D NumPy array named Karan             :  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimension of the array                         :  1
Shape of the array                             :  (25,)
Total elements in the array                    :  25
Data type of each element                      :  float64
Total number of bytes consumed by the array    :  200

Array after using reshape(5,5)                 :
 [[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]

Transpose of the array using reshape()         :
 [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


In [54]:
"""
Question 5:
Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.
"""

ucs420_Karan = np.array([[10, 20, 30, 40],[50,60,70,80],[90,15,20,35]])
print("Created 2-D array                      :\n", ucs420_Karan)

print("Mean of the created array              : ", np.mean(ucs420_Karan))
print("Median of the created array            : ", np.median(ucs420_Karan))
print("Maximum of the created array           : ", np.max(ucs420_Karan))
print("Minimum of the created array           : ", np.min(ucs420_Karan))
print("Unique elements of the created array   : ", np.unique(ucs420_Karan))

reshaped_ucs420_Karan = ucs420_Karan.reshape(4,3)
print("\nReshaped array                         :\n", reshaped_ucs420_Karan)

resized_ucs420_Karan = np.resize(ucs420_Karan,(2,3))
print("\nResized array                          :\n", resized_ucs420_Karan)

Created 2-D array                      :
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean of the created array              :  43.333333333333336
Median of the created array            :  37.5
Maximum of the created array           :  90
Minimum of the created array           :  10
Unique elements of the created array   :  [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array                         :
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array                          :
 [[10 20 30]
 [40 50 60]]
